spring:
  application:
    name: data-provider

  datasource:
    url: jdbc:postgresql://localhost:5432/alarmdb
    username: alarmuser
    password: alarmpass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest