version: "3.8"
services:
  postgres:
    image: postgres:15
    container_name: alarm_postgres
    restart: always
    environment:
      POSTGRES_DB: alarmdb
      POSTGRES_USER: alarmuser
      POSTGRES_PASSWORD: alarmpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: alarm_rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  postgres_data:
