spring:
  application:
    name: data-provider
  datasource:
    url: ${DATAPROVIDER_DB_URL:jdbc:postgresql://localhost:5432/alarmdb}
    username: ${DATAPROVIDER_DB_USERNAME:alarmuser}
    password: ${DATAPROVIDER_DB_PASSWORD:alarmpass}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    schemas: ${DATAPROVIDER_DB_SCHEMA:public}
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}
app:
  messaging:
    exchange: ${APP_MESSAGING_EXCHANGE:currency.alerts.exchange}
    queue: ${APP_MESSAGING_QUEUE:currency.alerts.queue}
    routing-key: ${APP_MESSAGING_ROUTING_KEY:currency.alerts.rate-change}
  security:
    jwt:
      secret: ${APP_SECURITY_JWT_SECRET:YWNtZWFybmVkLXNlY3VyZS1rZXktZm9yLWFsYXJtLXdhbHV0LWFwcA==}
      expiration: ${APP_SECURITY_JWT_EXPIRATION:PT24H}
server:
  port: ${SERVER_PORT:8080}