spring:
  application:
    name: data-gatherer
  datasource:
    url: ${DATAGATHERER_DB_URL:jdbc:postgresql://localhost:5432/datagatherer}
    username: ${DATAGATHERER_DB_USERNAME:datagatherer}
    password: ${DATAGATHERER_DB_PASSWORD:datagatherer}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    schemas: ${DATAGATHERER_DB_SCHEMA:public}
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

app:
  exchange-rate:
    app-id: ${OXR_APP_ID:demo}
    base-url: https://openexchangerates.org/api
    latest-endpoint: /latest.json
    base-currency: USD
    default-threshold-percent: 1.0
    custom-thresholds:
      PLN: 0.5
      EUR: 0.75
  messaging:
    exchange: currency.alerts.exchange
    queue: currency.alerts.queue
    routing-key: currency.alerts.rate-change
  scheduling:
    fetch-cron: "0 0 * * * *"